module.exports = {
  ADD_CURRENTUSER: 'ADD_CURRENTUSER',
  REMOVE_CURRENTUSER: 'REMOVE_CURRENTUSER',
  ADD_NOTIFICATIONS: 'ADD_NOTIFICATIONS',
  ADD_NOTIFICATIONCOUNT: 'ADD_NOTIFICATIONCOUNT',
  DELETE_NOTIFICATIONCOUNT : 'DELETE_NOTIFICATIONCOUNT',
  ADD_IP : 'ADD_IP'
};